INFERANALYZE = '/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/infer-analyze' --results-dir '/Users/BoBo/Desktop/termproject/infer-out' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
